//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UfanetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        public int equipment_id { get; set; }
        public string equipment_name { get; set; }
        public string model { get; set; }
        public string serial_number { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
