//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UfanetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class requests
    {
        public int request_id { get; set; }
        public string request_number { get; set; }
        public int subscriber_id { get; set; }
        public int employee_id { get; set; }
        public int tariff_id { get; set; }
        public Nullable<System.DateTime> request_date { get; set; }
        public Nullable<System.DateTime> completion_date { get; set; }
        public string status { get; set; }
        public string comment { get; set; }
    
        public virtual employees employees { get; set; }
        public virtual subscribers subscribers { get; set; }
        public virtual tariffs tariffs { get; set; }
    }
}
